//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locadora_Veiculo_MVC5
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Automovel
    {
        public Automovel()
        {
            this.Locacao = new HashSet<Locacao>();
        }
    
        //[Display(Name="Código Altomovel")]
        [Required()]
        public int AutomovelID { get; set; }
        [Display(Name="Código Modelo")]
        [Required()]
        public Nullable<int> ModeloID { get; set; }
        [Display(Name="Placa")]
        public string PlacaAutomovel { get; set; }
        [Display(Name="Ano")]
        public string AnoAutomovel { get; set; }

        public virtual Marca Marca { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual ICollection<Locacao> Locacao { get; set; }
    }
}
