//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locadora_Veiculo_MVC5
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Locadora_Veiculo_MVC5.Models;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Locacao = new HashSet<Locacao>();
        }
    
        //[Display(Name="Código Cliente")]
        [Required(ErrorMessage = "Campo obrigatorio")]
        public int ClienteID { get; set; }

        [Display(Name="Nome do Cliente")]
        [Required(ErrorMessage = "Campo obrigatorio")]
        public string NomeCliente { get; set; }

        [Display(Name="E-mail")]
        [DataType(DataType.EmailAddress,ErrorMessage="Formato de Email Invalido !")]
        public string EmailCliente { get; set; }

        [Display(Name="CPF")]
        [Required(ErrorMessage = "Campo obrigatorio")]
        [CustonValidationCPF(ErrorMessage="CPF Inválido !")]
        public string CpfCliente { get; set; }

        [Required(ErrorMessage = "Campo obrigatorio")]
        [DataType(DataType.Date,ErrorMessage="Formato de data invalido ! - Formato correto dd/mm/aaaa")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name="Data de Cadastro")]
        public Nullable<System.DateTime> DataCadastro { get; set; }
    
        public virtual ICollection<Locacao> Locacao { get; set; }
    }
}
