//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locadora_Veiculo_MVC5
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Marca
    {
        public Marca()
        {
            this.Modelo = new HashSet<Modelo>();
        }
    
        [Display(Name="Código Marca")]
        [Required(ErrorMessage = "Campo obrigatorio")]
        public int MarcaID { get; set; }
        [Display(Name="Nome Marca")]
        [Required(ErrorMessage = "Campo obrigatorio")]
        public string NomeMarca { get; set; }
    
        public virtual ICollection<Modelo> Modelo { get; set; }
        
    }
}
