//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locadora_Veiculo_MVC5
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Modelo
    {
        public Modelo()
        {
            this.Automovel = new HashSet<Automovel>();
        }
    
        [Display(Name="Código Modelo")]
        [Required(ErrorMessage = "Campo obrigatorio")]
        public int ModeloID { get; set; }
        [Display(Name="Código Marca")]
        [Required(ErrorMessage = "Campo obrigatorio")]
        public Nullable<int> MarcaID { get; set; }
        [Display(Name="Nome Modelo")]
        [Required(ErrorMessage = "Campo obrigatorio")]
        public string NomeModelo { get; set; }
    
        public virtual ICollection<Automovel> Automovel { get; set; }
        public virtual Marca Marca { get; set; }
    }
}
